name: Docs

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs
        
    - name: Build Documentation
      run: |
        python redditdownloader/tools/doc_builder.py
        mkdocs build
        
    - name: Deploy to gh-pages branch
      uses: peaceiris/actions-gh-pages@v2.9.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./site
      with:
        username: "shadow-bot"
        useremail: "github_bot@github.com"


  build_loc_badge:
    runs-on: ubuntu-latest
    name: Build LoC Badge
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Generate Badge
        uses: shadowmoose/GHA-LoC-Badge@1.0.0
        id: badge
        with:
          debug: true
          directory: ./
          badge: ./output/loc-badge.svg
          ignore: '**/js/libs/**|**/web/img/**|**.zip|**/alertify.css'

      - name: Print the output
        run: |
          echo "Scanned: ${{ steps.badge.outputs.counted_files }}";
          echo "Line Count: ${{ steps.badge.outputs.total_lines }}";

      - name: Deploy Badge
        uses: peaceiris/actions-gh-pages@v2.9.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: project-badges
          PUBLISH_DIR: ./output
        with:
          username: "shadow-bot"
          useremail: "github_bot@github.com"
